Bismillah Her Hayrın Başıdır....

In [12]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [13]:
df = pd.read_csv("original.csv")
df = df.iloc[:,1: len(df)]
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [14]:
X = df.drop('sales',axis=1)
y = df[["sales"]]

In [15]:
y

     sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
5      7.2
6     11.8
7     13.2
8      4.8
9     10.6
10     8.6
11    17.4
12     9.2
13     9.7
14    19.0
15    22.4
16    12.5
17    24.4
18    11.3
19    14.6
20    18.0
21    12.5
22     5.6
23    15.5
24     9.7
25    12.0
26    15.0
27    15.9
28    18.9
29    10.5
..     ...
170    8.4
171   14.5
172    7.6
173   11.7
174   11.5
175   27.0
176   20.2
177   11.7
178   11.8
179   12.6
180   10.5
181   12.2
182    8.7
183   26.2
184   17.6
185   22.6
186   10.3
187   17.3
188   15.9
189    6.7
190   10.8
191    9.9
192    5.9
193   19.6
194   17.3
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [16]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
5      8.7   48.9       75.0
6     57.5   32.8       23.5
7    120.2   19.6       11.6
8      8.6    2.1        1.0
9    199.8    2.6       21.2
10    66.1    5.8       24.2
11   214.7   24.0        4.0
12    23.8   35.1       65.9
13    97.5    7.6        7.2
14   204.1   32.9       46.0
15   195.4   47.7       52.9
16    67.8   36.6      114.0
17   281.4   39.6       55.8
18    69.2   20.5       18.3
19   147.3   23.9       19.1
20   218.4   27.7       53.4
21   237.4    5.1       23.5
22    13.2   15.9       49.6
23   228.3   16.9       26.2
24    62.3   12.6       18.3
25   262.9    3.5       19.5
26   142.9   29.3       12.6
27   240.1   16.7       22.9
28   248.8   27.1       22.9
29    70.6   16.0       40.8
..     ...    ...        ...
170   50.0   11.6       18.4
171  164.5   20.9       47.4
172   19.6   20.1       17.0
173  168.4    7.1       12.8
174  222.4    3.4       13.1
175  276.9   48.9       41.8
176  248.4   30.2       20.3
177  170.2    7.8       35.2
178  276.7    2.3       23.7
179  165.6   10.0       17.6
180  156.6    2.6        8.3
181  218.5    5.4       27.4
182   56.2    5.7       29.7
183  287.6   43.0       71.8
184  253.8   21.3       30.0
185  205.0   45.1       19.6
186  139.5    2.1       26.6
187  191.1   28.7       18.2
188  286.0   13.9        3.7
189   18.7   12.1       23.4
190   39.5   41.1        5.8
191   75.5   10.8        6.0
192   17.2    4.1       31.6
193  166.8   42.0        3.6
194  149.7   35.6        6.0
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [17]:
#Statsmodel ile model kurmak...

In [18]:
import statsmodels.api as sm

In [19]:
lm = sm.OLS(y,X)

In [20]:
model = lm.fit()#

In [21]:
model.summary()# modelin özetlirini verir
#çoklu dogrusal modelin çıktısı aşağıdadır.
#R^2 bağımsız değişkenlerin bağımlı değişkeni açıklama yüzdesi, Veri setine yeni değerler eklendiğinde bu değer şişer.
#Adj.R^2 düzeltimiş R^2 değeridir. R^2 deki şişmeyi önlemek amacı ile yapılır.
#F-statistic modelin anlamlılığının test etmek için kullanılmaktadır.
#Prob(F-statistic) modelin anlamlığını verir, 0.05'ten küçük olduğu için model anlamlıdır.
#coef kurulacak olan modeldeki bağımsız değişkenlerin katsayılarını temsil etmektedir.
#P>|t| bunun manası modellememk için kullandığımız bğtğn değişkenler anlamldır. Buradaki hipotezler değişkenin anlamlı olmadığını söyleyen hipotezlerdir. Ve bu değerler 0.05'ten küçük olduğu için reddedilir buda bu modeldeki kullanılan değişkenlerin anlamlı oldupu anlamına gelmektedir. 
#Katsayıların yorumlanması: Tv için; diğer değişkenler sabit varsayıldığında TV harcamalarında meydana gelebilecek bir birimlik artış bagımlı değikende 0.0538 birimlik bir artışa sebeb olacaktır denmektedir.

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.982
Method:                 Least Squares   F-statistic:                     3566.
Date:                Sat, 28 Mar 2020   Prob (F-statistic):          2.43e-171
Time:                        14:28:02   Log-Likelihood:                -423.54
No. Observations:                 200   AIC:                             853.1
Df Residuals:                     197   BIC:                             863.0
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
##scikit learn ile model kurmak

In [23]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [24]:
model = lm.fit(X,y)

In [25]:
model.intercept_

array([2.93888937])

In [26]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Tahmin

sales = 2.94 + TV * 0.04 + radio * 0.18 - newspaper * 0.001

In [27]:
yeni_veri = [[30],[12],[13]]

In [28]:
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T

In [29]:
yeni_veri

    0   1   2
0  30  12  13

In [30]:
model.predict(yeni_veri)

array([[6.56070153]])